# PROGRAM TO CALCULATE NUMBER OF DIGITS IN A NUMBER
number = int(input("ENTER A NUMBER ="))
count = 0
# EXECUTING LOOP UNTILL A NUMBER IS GRETER THAN ZERO
while number > 0:
    # DIVING NUMBER BY 10 SO THAT WE CAN BREAK INTO TENS E.G 100 IT BECOMES 10 THE 1 THEN 0 THIS MANS COUNT WILL HAVE VALUE 3
    number = int(number/10)
    count = count+1
print("NUMBER OF DIGIT IN THE GIVEN NUMBER ARE ", count)
