# PROGRAM TO FIND THE ODD NUMBER BETWEEN TWO NUMBERS
# TAKING NUMBER 1 AS INPUT
number1 = int(input(" ENTER FIRST NUMBER ="))
# TAKING NUMBER 2 AS INPUT
number2 = int(input(" ENTER SECOND NUMBER ="))
# INITIALIZING IT BY 1 TO ELIMINATE GARBAGE VALUE
sum1 = 0
print("ODD NUMBERS BETWEEN TWO NUMBERS ARE =")
for i in range(number1, number2+1):
    # BY APPLYING CONDITION TO FIND THAT I IS A EVEN NUMBER OR ODD
    if(i % 2 != 0):
        print(i)
# FINDING SUM
        sum1 = sum1+i
print("SUM OF THE ODD NUMBERS BETWEEN TWO GIVEN NUMBERS ARE =", sum1)
